### ISSUE TITLE
I have never seen such wonderful GAIL codes before！！！

### ISSUE THREAD

**Issue by Rafinic-Xu** [Johnny-Zhang92/IRL-Essential-Code#1]
我从未见过如此美妙的GAIL代码！！！
Ich habe noch nie so wunderbare GAIL-Codes gesehen！！！
こんなに素敵なGAILコードを見たのは初めてです！！！
Я никогда раньше не видел таких замечательных кодов GAIL！！！！
Je n'ai jamais vu d'aussi merveilleux codes GAIL avant...
Nunca había visto unos códigos GAIL tan maravillosos！！！

**Comment by Rafinic-Xu** [comment]
Oh my God! It is fucking good!

**Comment by shuoye1000** [comment]
Non ho mai visto un codice GAIL così meraviglioso!!!
Nunca he visto un código GAIL tan maravilloso!!!

**Comment by Rafinic-Xu** [comment]
> Non ho mai visto un codice GAIL così meraviglioso!!! Nunca he visto un código GAIL tan maravilloso!!!

Wang zhuo？

**Comment by MNTMDEV** [comment]
Yes,it is!

**Comment by MNTMDEV** [comment]
> > Non ho mai visto un codice GAIL così meraviglioso!!! Nunca he visto un código GAIL tan maravilloso!!!
> 
> Wang zhuo？

Yes,it is.
